apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: daniel-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: daniel-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/leichus/nyc-hackathon-2022
      ref:
        branch: master
